import React,{useEffect,useMemo,useState} from 'react'
import { useAuth } from '../auth/AuthContext'
import { collection, query, where, onSnapshot } from 'firebase/firestore'
import { db } from '../firebase/init'
import { Chart as ChartJS, ArcElement, Tooltip, Legend, CategoryScale, LinearScale, BarElement, PointElement, LineElement } from 'chart.js'
import { Pie, Line } from 'react-chartjs-2'
import { exportToCSV } from '../utils/csvExport'
import Card from '../components/Card'
ChartJS.register(ArcElement, Tooltip, Legend, CategoryScale, LinearScale, BarElement, PointElement, LineElement)
export default function AnalysisPage(){const { user } = useAuth();const [expenses,setExpenses]=useState([]);const [from,setFrom]=useState('');const [to,setTo]=useState('');useEffect(()=>{if(!user) return;const q=query(collection(db,'expenses'),where('userId','==',user.uid));const unsub=onSnapshot(q,snap=>{const arr=[];snap.forEach(d=>arr.push({id:d.id,...d.data()}));setExpenses(arr)});return ()=>unsub()},[user]);const filtered=useMemo(()=>{if(!from&&!to) return expenses;const f=new Date(from||'1970-01-01');const t=new Date(to||'2100-01-01');return expenses.filter(e=>{const d=new Date(e.date);return d>=f&&d<=t})},[expenses,from,to]);const total=filtered.reduce((s,e)=>s+(parseFloat(e.amount)||0),0);const byCategory=useMemo(()=>{const map={};filtered.forEach(e=>{map[e.category]=(map[e.category]||0)+(parseFloat(e.amount)||0)});return map},[filtered]);const pieData={labels:Object.keys(byCategory),datasets:[{data:Object.values(byCategory),label:'Amount'}]};const monthly=useMemo(()=>{const map={};filtered.forEach(e=>{const d=new Date(e.date);const key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;map[key]=(map[key]||0)+(parseFloat(e.amount)||0)});const entries=Object.entries(map).sort();return{labels:entries.map(e=>e[0]),data:entries.map(e=>e[1])}},[filtered]);const lineData={labels:monthly.labels,datasets:[{label:'Monthly',data:monthly.data,tension:0.3}]}
function downloadCSV(){const data=filtered.map(e=>({Date:e.date,Category:e.category,Description:e.description||'',Amount:e.amount,Notes:e.notes||''}));exportToCSV(data,`analysis-${new Date().toISOString().slice(0,10)}.csv`)}
return (<div className='space-y-4'><div className='flex flex-col md:flex-row md:items-center md:justify-between gap-3'><h2 className='text-xl font-semibold'>Analysis</h2><div className='flex items-center gap-2'><input type='date' className='p-2 border rounded' value={from} onChange={e=>setFrom(e.target.value)} /><input type='date' className='p-2 border rounded' value={to} onChange={e=>setTo(e.target.value)} /><button onClick={downloadCSV} className='px-3 py-2 bg-gray-100 hover:bg-gray-200 rounded'>Export CSV</button></div></div><div className='grid md:grid-cols-3 gap-4'><Card title='Summary'><div className='space-y-2'><div className='flex justify-between'><span>Total</span><strong>{total.toFixed(2)}</strong></div><div className='flex justify-between'><span>Entries</span><strong>{filtered.length}</strong></div></div></Card><Card title='Category breakdown' className='md:col-span-2'><div className='h-60'><Pie data={pieData}/></div></Card><Card title='Monthly trend' className='md:col-span-3'><div className='h-48'><Line data={lineData}/></div></Card><Card title='Detailed list' className='md:col-span-3'><div className='overflow-x-auto'><table className='w-full text-sm'><thead className='text-left border-b'><tr><th className='py-2'>Date</th><th>Category</th><th>Description</th><th className='text-right'>Amount</th></tr></thead><tbody>{filtered.map(e=>(<tr key={e.id} className='odd:bg-gray-50'><td className='py-2'>{e.date}</td><td>{e.category}</td><td>{e.description||'-'}</td><td className='text-right font-medium'>{e.amount}</td></tr>))}</tbody></table></div></Card></div></div>)}